# Generated by Django 5.2.17 for Location Floor Plan Phase 2.

import uuid

import django.core.serializers.json
import django.core.validators
import django.db.models.deletion
import nautobot.core.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("dcim", "0097_virtualdevicecontext_controller_managed_device_group"),
        ("extras", "0145_objectmetadata_assigned_object_type_cascade"),
    ]

    operations = [
        migrations.CreateModel(
            name="FloorPlan",
            fields=[
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "_custom_field_data",
                    models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("tags", nautobot.core.models.fields.TagsField(through="extras.TaggedItem", to="extras.Tag")),
                (
                    "logical_width",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(1000000),
                        ]
                    ),
                ),
                (
                    "logical_height",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(1000000),
                        ]
                    ),
                ),
                ("background", models.FileField(blank=True, null=True, upload_to="location_floor_plan/backgrounds/")),
                ("revision", models.PositiveBigIntegerField(default=1, editable=False)),
                (
                    "location",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="location_floor_plan_map",
                        to="dcim.location",
                    ),
                ),
            ],
            options={
                "verbose_name": "floor plan",
                "verbose_name_plural": "floor plans",
                "ordering": ["location__name"],
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name="LocationPlacement",
            fields=[
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "_custom_field_data",
                    models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("tags", nautobot.core.models.fields.TagsField(through="extras.TaggedItem", to="extras.Tag")),
                ("geometry", models.JSONField()),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="location_floor_plan_placements",
                        to="dcim.location",
                    ),
                ),
                (
                    "floor_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="location_placements",
                        to="location_floor_plan.floorplan",
                    ),
                ),
            ],
            options={
                "verbose_name": "location placement",
                "verbose_name_plural": "location placements",
                "ordering": ["location__name"],
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name="RackPlacement",
            fields=[
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "_custom_field_data",
                    models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("tags", nautobot.core.models.fields.TagsField(through="extras.TaggedItem", to="extras.Tag")),
                ("x", models.PositiveIntegerField()),
                ("y", models.PositiveIntegerField()),
                ("width", models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ("height", models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                (
                    "floor_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rack_placements",
                        to="location_floor_plan.floorplan",
                    ),
                ),
                (
                    "rack",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="location_floor_plan_placements",
                        to="dcim.rack",
                    ),
                ),
            ],
            options={
                "verbose_name": "rack placement",
                "verbose_name_plural": "rack placements",
                "ordering": ["rack__name"],
            },
            bases=(models.Model,),
        ),
        migrations.AddConstraint(
            "floorplan",
            models.CheckConstraint(condition=models.Q(("logical_width__gte", 1)), name="location_floor_plan_map_width_gte_1"),
        ),
        migrations.AddConstraint(
            "floorplan",
            models.CheckConstraint(
                condition=models.Q(("logical_height__gte", 1)), name="location_floor_plan_map_height_gte_1"
            ),
        ),
        migrations.AddConstraint(
            "floorplan",
            models.CheckConstraint(
                condition=models.Q(("logical_width__lte", 1000000)), name="location_floor_plan_map_width_lte_max"
            ),
        ),
        migrations.AddConstraint(
            "floorplan",
            models.CheckConstraint(
                condition=models.Q(("logical_height__lte", 1000000)), name="location_floor_plan_map_height_lte_max"
            ),
        ),
        migrations.AddConstraint(
            "floorplan",
            models.CheckConstraint(condition=models.Q(("revision__gte", 1)), name="location_floor_plan_map_revision_gte_1"),
        ),
        migrations.AddConstraint(
            "locationplacement",
            models.UniqueConstraint(
                fields=("floor_plan", "location"), name="location_floor_plan_unique_location_placement"
            ),
        ),
        migrations.AddConstraint(
            "rackplacement",
            models.UniqueConstraint(fields=("floor_plan", "rack"), name="location_floor_plan_unique_rack_placement"),
        ),
        migrations.AddConstraint(
            "rackplacement",
            models.CheckConstraint(condition=models.Q(("width__gte", 1)), name="location_floor_plan_rack_width_gte_1"),
        ),
        migrations.AddConstraint(
            "rackplacement",
            models.CheckConstraint(condition=models.Q(("height__gte", 1)), name="location_floor_plan_rack_height_gte_1"),
        ),
    ]
